# Generated by Django 3.2.12 on 2022-04-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search_keys',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
